PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX nobel: <http://data.nobelprize.org/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX yago: <http://yago-knowledge.org/resource/>
PREFIX viaf: <http://viaf.org/viaf/>
PREFIX meta: <http://www4.wiwiss.fu-berlin.de/bizer/d2r-server/metadata#>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX d2r: <http://sites.wiwiss.fu-berlin.de/suhl/bizer/d2r-server/config.rdf#>
PREFIX dbpedia: <http://dbpedia.org/resource/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX map: <http://data.nobelprize.org/resource/#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX freebase: <http://rdf.freebase.com/ns/>
PREFIX dbpprop: <http://dbpedia.org/property/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?givenName ?familyName ?var ?uni
WHERE {
  ?laur rdf:type nobel:Laureate .
  ?laur foaf:familyName ?familyName .
  ?laur foaf:givenName ?givenName .
  #?laur dbo:birthPlace ?Country .
  #?Country rdfs:label ?test .
  ?laur nobel:nobelPrize ?prijs .
  ?prijs nobel:category ?var .
  ?laur nobel:laureateAward ?award .
  ?award nobel:university ?uni .
}
