PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX dbpedia2: <http://dbpedia.org/property/>
PREFIX dbpedia: <http://dbpedia.org/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX : <http://dbpedia.org/resource/>

SELECT DISTINCT ?givenname ?surname ?by ?country ?almaMater WHERE {
# Resource is replaced by a resource on dbpedia
<$RESOURCE$> foaf:givenName ?givenname .
<$RESOURCE$> foaf:surname ?surname .
<$RESOURCE$> dbo:birthPlace ?c .
        ?c dbo:country ?co .
        ?co rdfs:label ?country .
      FILTER langMatches (lang(?country), 'en' )
<$RESOURCE$> dbo:almaMater ?mater .
?mater rdfs:label ?almaMater .
FILTER langMatches (lang(?almaMater), 'en' )
<$RESOURCE$> dbo:birthYear ?by .
FILTER (?by > "1850"^^<http://www.w3.org/2001/XMLSchema#gYear>)
}



